__put_name_here__
zeriontech/the_token_fund_asset_parser pull request #4
Opened 2017-07-18 21:44 UTC by vovapi

## What's done:
* Remove callback method of processing async fetched data.
* Add config file (default location is `configs/main.yml`
* Separate fetch and update functions
* Some refactoring here and there
* Add support for `/token_price` endpoint
## TODO
* Proper logging
* Fetched data caching

2017-07-19 21:27 UTC, bashalex requested changes

2017-07-19 21:27 UTC, bashalex commented on models/google_sheets_api.py
> +            flow = client.flow
??

2017-07-19 21:27 UTC, bashalex commented on models/coinmarketcap.py
> +    # Coins that doesnt have
Coins that do not have what?

2017-07-19 21:27 UTC, bashalex commented on README.md
> +
I would add that by default `configs/main.yml` fail is used.

2017-07-19 21:27 UTC, bashalex commented on models/google_sheets_api.py
>          http = self._credentials.authorize(httplib2.Http())
Let's add `cache_discovery=False` to `discovery.build()` to get rid of warning messages as suggested here: https://stackoverflow.com/a/44518587/4793743

2017-07-19 21:27 UTC, bashalex commented on update_table.py
> +import asyncio
redundant dependency

2017-07-19 21:27 UTC, bashalex commented on update_table.py
> +    date = time.strftime('%Y-%m-%d %H:%M %Z')
I think would be better to convert datetime to UTC and print it without timezone

2017-07-20 12:17 UTC, vovapi commented on models/google_sheets_api.py
>          http = self._credentials.authorize(httplib2.Http())
@bashalex done in 08067ff

2017-07-20 12:17 UTC, vovapi commented on models/google_sheets_api.py
> +            flow = client.flow
@bashalex fixed in 08067ff

2017-07-20 12:20 UTC, vovapi commented on models/coinmarketcap.py
> +    # Coins that doesnt have
@bashalex this used to be a list for coins that does not have proper info (e.g. `{"update_time": none}`). I've moved from this, but it is somehow got here.
Fixed in 9871d9d

2017-07-20 12:50 UTC, vovapi commented on update_table.py
> +    date = time.strftime('%Y-%m-%d %H:%M %Z')
@bashalex Done in cf85346

2017-07-20 12:51 UTC, vovapi commented on update_table.py
> +import asyncio
cf85346

2017-07-20 15:06 UTC, bashalex approved these changes

2017-07-20 15:07 UTC, merged